image:
  repository: tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.17.1

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

tautulliConfig:
  additionalEnvs: []

tautulliNetwork:
  webPort: 30047
  hostNetwork: false

tautulliRunAs:
  user: 568
  group: 568

tautulliStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
